- fixing tooltip text [AD-560]

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -9,23 +9,41 @@ C_BROWN='\e[33m'
 C_YELLOW='\e[93m'
 C_GREY='\e[90m'
 
+IS_MERGE=$(git rev-parse -q --verify MERGE_HEAD)
+PRODUCTION_BRANCH="production"
+LIVE_BRANCHES=("staging" "$PRODUCTION_BRANCH")
+CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+
+block_prohibit_merges() {
+	local MERGED_BRANCH=$(git rev-parse --abbrev-ref HEAD@{upstream})
+	local ALLOWED_BRANCH="master"
+	if [[ "$PRODUCTION_BRANCH" == "$CURRENT_BRANCH" && "$MERGED_BRANCH" != "$ALLOWED_BRANCH" ]]; then
+		echo "Error: Merging $MERGED_BRANCH directly into $CURRENT_BRANCH is not allowed. Please merge from $ALLOWED_BRANCH."
+		exit 1
+	fi
+}
+
+block_prohibit_commits() {
+	for BRANCH in "${LIVE_BRANCHES[@]}"; do
+		if [[ "$CURRENT_BRANCH" == "$BRANCH" ]]; then
+			printf "${C_RED}\n"
+			echo "Error: You are trying to commit directly to the $BRANCH branch."
+			echo "Please commit your changes to a feature branch and then merge into the $BRANCH branch instead."
+			printf "\n${C_RED}Aborting commit.${C_RESET}\n\n"
+			exit 1
+		fi
+	done
+}
+
 printf "${C_GREEN}Pre-commit hook running...${C_RESET}\n\n"
+if [[ -n "$IS_MERGE" ]]; then
+	printf "\n[MERGE DETECTED] ... skipping code checks\n"
+	block_prohibit_merges
+	exit 0
+fi
 
 # Commits should not be made directly on Staging branch.
-# (Do work in feature branch and then merge into Staging branch)
-
-FORBIDDEN="staging"
-THIS_BRANCH=$(git rev-parse --abbrev-ref HEAD)
-
-if [[ "$THIS_BRANCH" == "$FORBIDDEN" ]] ; then
-  if [ ! -e ".git/MERGE_MODE" ]; then
-    printf "\e[31m\n"
-    echo "${C_RED}Error${C_RESET}: You are trying to commit directly on the $FORBIDDEN branch."
-    echo "Please commit in a feature branch and then merge into $FORBIDDEN branch instead."
-    printf "\n\e[1mAborting commit.\e[0m\n\n"
-    exit 1
-  fi
-fi
+block_prohibit_commits
 
 # Run code style checks on staged files
 
@@ -88,10 +106,3 @@ if ! $PASS; then
   printf "\nYou can run '\e[1mnpm run eslint\e[0m' to view ESLint code quality issues, if any.\n\n"
   exit 1
 fi
-
-# printf "\n\e[32mRunning Jest...\e[0m\n"
-# npm test -- --ci --findRelatedTests $STAGED_FILES
-# if [[ "$?" != 0 ]]; then
-#   printf "\e[31mEither Jest tests failed, or code coverage is not complete. Please fix and try again.\e[0m\n"
-#   exit 2
-# fi
